export const POST_LOGIN_REQUESTED = "POST_LOGIN_REQUESTED";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";

export const POST_REGISTER_REQUESTED = "POST_REGISTER_REQUESTED";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILED = "POST_REGISTER_FAILED";
