export const POST_LOGIN_REQUESTED = "POST_LOGIN_REQUESTED";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";

export const POST_REGISTER_REQUESTED = "POST_REGISTER_REQUESTED";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILED = "POST_REGISTER_FAILED";

export const RESET = "RESET";

//DO_TEST

export const SET_SELECTED_QUESTION = "SET_SELECTED_QUESTION";
export const SET_LIST_QUESTION = "SET_LIST_QUESTION";
export const SET_TEST_DATA = "SET_TEST_DATA";
