//AUTH
export const POST_LOGIN_REQUESTED = "POST_LOGIN_REQUESTED";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";

export const POST_REGISTER_REQUESTED = "POST_REGISTER_REQUESTED";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILED = "POST_REGISTER_FAILED";

export const RESET = "RESET";

//DO_TEST

export const SET_SELECTED_QUESTION = "SET_SELECTED_QUESTION";
export const SET_LIST_QUESTION = "SET_LIST_QUESTION";
export const SET_TEST_DATA = "SET_TEST_DATA";

//QUESTION
export const POST_CREATE_QUESTION_REQUEST = "POST_CREATE_QUESTION_REQUEST";
export const POST_CREATE_QUESTION_SUCCESS = "POST_CREATE_QUESTION_SUCCESS";
export const POST_CREATE_QUESTION_FAILED = "POST_CREATE_QUESTION_FAILED";

export const SEARCH_QUESTION_REQUEST = "SEARCH_QUESTION_REQUEST";
export const SEARCH_QUESTION_SUCCESS = "SEARCH_QUESTION_SUCCESS";
export const SEARCH_QUESTION_FAILED = "SEARCH_QUESTION_FAILED";

export const GET_LIST_QUESTION_REQUEST = "GET_LIST_QUESTION_REQUEST";
export const GET_LIST_QUESTION_SUCCESS = "GET_LIST_QUESTION_SUCCESS";
export const GET_LIST_QUESTION_FAILED = "GET_LIST_QUESTION_FAILED";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAILED = "UPDATE_QUESTION_FAILED";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAILED = "DELETE_QUESTION_FAILED";

export const GET_QUESTION_DETAIL_REQUEST = "GET_QUESTION_DETAIL_REQUEST";
export const GET_QUESTION_DETAIL_SUCCESS = "GET_QUESTION_DETAIL_SUCCESS";
export const GET_QUESTION_DETAIL_FAILED = "GET_QUESTION_DETAIL_FAILED";

//TEST
export const CREATE_TEST_REQUEST = "CREATE_TEST_REQUEST";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";
export const CREATE_TEST_FAILED = "CREATE_TEST_FAILED";

export const UPDATE_TEST_REQUEST = "UPDATE_TEST_REQUEST";
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";
export const UPDATE_TEST_FAILED = "UPDATE_TEST_FAILED";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_FAILED = "DELETE_TEST_FAILED";

export const SEARCH_TEST_REQUEST = "SEARCH_TEST_REQUEST";
export const SEARCH_TEST_SUCCESS = "SEARCH_TEST_SUCCESS";
export const SEARCH_TEST_FAILED = "SEARCH_TEST_FAILED";

export const GET_ALL_TEST_REQUEST = "GET_ALL_TEST_REQUEST";
export const GET_ALL_TEST_SUCCESS = "GET_ALL_TEST_SUCCESS";
export const GET_ALL_TEST_FAILED = "GET_ALL_TEST_FAILED";

export const GET_PUBLIC_TEST_REQUEST = "GET_PUBLIC_TEST_REQUEST";
export const GET_PUBLIC_TEST_SUCCESS = "GET_PUBLIC_TEST_SUCCESS";
export const GET_PUBLIC_TEST_FAILED = "GET_PUBLIC_TEST_FAILED";

export const GET_TEST_EXECUTE_NUMBER_REQUEST =
  "GET_TEST_EXECUTE_NUMBER_REQUEST";
export const GET_TEST_EXECUTE_NUMBER_SUCCESS =
  "GET_TEST_EXECUTE_NUMBER_SUCCESS";
export const GET_TEST_EXECUTE_NUMBER_FAILED = "GET_TEST_EXECUTE_NUMBER_FAILED";

export const GET_TEST_DETAIL_REQUEST = "GET_TEST_DETAIL_REQUEST";
export const GET_TEST_DETAIL_SUCCESS = "GET_TEST_DETAIL_SUCCESS";
export const GET_TEST_DETAIL_FAILED = "GET_TEST_DETAIL_FAILED";

export const PUBLISH_TEST_REQUEST = "PUBLISH_TEST_REQUEST";
export const PUBLISH_TEST_SUCCESS = "PUBLISH_TEST_SUCCESS";
export const PUBLISH_TEST_FAILED = "PUBLISH_TEST_FAILED";

export const SET_NEW_SELECTED_QUESTION = "SET_NEW_SELECTED_QUESTION";

export const SET_TEST_SELECTED_QUESTION = "SET_TEST_SELECTED_QUESTION";
export const SET_NEW_TEST = "SET_NEW_TEST";

//USER

export const GET_LIST_USER_REQUEST = "GET_LIST_USER_REQUEST";
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS";
export const GET_LIST_USER_FAILED = "GET_LIST_USER_FAILED";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILED = "SEARCH_USER_FAILED";

//RESULT

export const GET_LIST_RESULT_REQUEST = "GET_LIST_RESULT_REQUEST";
export const GET_LIST_RESULT_SUCCESS = "GET_LIST_RESULT_SUCCESS";
export const GET_LIST_RESULT_FAILED = "GET_LIST_RESULT_FAILED";

export const GET_RESULT_DETAIL_REQUEST = "GET_RESULT_DETAIL_REQUEST";
export const GET_RESULT_DETAIL_SUCCESS = "GET_RESULT_DETAIL_SUCCESS";
export const GET_RESULT_DETAIL_FAILED = "GET_RESULT_DETAIL_FAILED";

export const POST_RESULT_REQUEST = "POST_RESULT_REQUEST";
export const POST_RESULT_SUCCESS = "POST_RESULT_SUCCESS";
export const POST_RESULT_FAILED = "POST_RESULT_FAILED";
